// import { Heading } from '@chakra-ui/react'
import { Box, Container, HStack, Text, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect } from 'react'
// import Image from 'next/image'
import Navbar from '../components/Navbar'
import Profile from '../components/Profile'
import TechStacks from '../components/TechStacks'
import Timeline from '../components/Timeline'
import styles from '../styles/Home.module.css'

function Home({profile}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
   
        <HStack p={"4"}>
          <VStack width={"25%"}>
            <Box>
                <Profile data = {profile}/>
            </Box>
            <TechStacks/>
            <Timeline/>
          </VStack>
          <Box>
            <Text>Main Content</Text>
          </Box>
        </HStack>
      
    </div>
  )
}
export async function getStaticProps(context) {
  let response = await fetch(`https://api.github.com/users/shivshankar0965`);
  let data = await response.json();
  return {
    props: {
      profile: data,
    }, 
  };
}
export default Home